In [5]:
import math
import os
import torch
import numpy  as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import warnings

from torch.optim              import AdamW
from torch.optim.lr_scheduler import OneCycleLR
from transformers             import EarlyStoppingCallback, Trainer, TrainingArguments, set_seed
from tsfm_public              import TimeSeriesForecastingPipeline 
from tsfm_public              import TimeSeriesPreprocessor
from tsfm_public              import TinyTimeMixerForPrediction
from tsfm_public              import TrackingCallback
from tsfm_public              import count_parameters
from tsfm_public              import get_datasets


from tsfm_public.toolkit.time_series_preprocessor import prepare_data_splits
from sklearn.metrics import precision_score, recall_score, f1_score
import ast
warnings.simplefilter(action='ignore', category=pd.errors.SettingWithCopyWarning)

from sklearn.metrics import precision_score, recall_score, f1_score



def metrics(actual, prediction):
    a = np.stack(actual).flatten()
    p = np.stack(prediction).flatten()
    mask = ~np.isnan(a) & ~np.isnan(p)
    a, p = a[mask], p[mask]

    mae  = np.mean(np.abs(a - p))
    rmse = np.sqrt(np.mean((a - p)**2))
    mape = np.mean(np.abs((a - p) / (a + 1e-8))) * 100

    actual_diff = np.sign(np.diff(a))
    pred_diff   = np.sign(np.diff(p))
    hit_rate = np.mean(actual_diff == pred_diff)

    actual_up = actual_diff > 0
    pred_up   = pred_diff   > 0
    precision = precision_score(actual_up, pred_up, zero_division=0)
    recall    = recall_score(actual_up, pred_up, zero_division=0)
    f1        = f1_score(actual_up, pred_up, zero_division=0)

    return dict(mae=mae, rmse=rmse, mape=mape,
                hit_rate=hit_rate,
                precision=precision, recall=recall, f1=f1)

device             = "cuda" if torch.cuda.is_available() else "cpu"
load_path          =  "ibm-granite/granite-timeseries-ttm-r2"
os.makedirs('fewshot_results', exist_ok=True)


tickers = ["AAPL",
           "TSLA",
           "XOM",
           "SPY",
           "JNJ",
           "AMD",
           "PG"
          ]

event_titles = ["AAPL – Crash & Rebound (2020-03-10)",
                "TSLA – High-Beta Cooling (2021-01-15)",
                "XOM – Oil Cycle Peak (2022-06-01)",
                "SPY – Drawdown Chop (2022-09-15)",
                "JNJ – Low-Volatility Stretch (2019-08-01)",
                "AMD – Tech Selloff (2018-10-10)",
                "PG – Macro-Irrelevant Calm (2015-06-15)"
                ]

starts = ["2019-09-02",
          "2020-07-01",
          "2021-10-01",
          "2022-01-03",
          "2018-11-01",
          "2018-04-02",
          "2014-12-01"
         ]

ends   = ["2020-06-01",
          "2021-06-30",
          "2022-09-30",
          "2022-12-30",
          "2020-01-01",
          "2019-03-29",
          "2016-01-01"
         ]

column_specifiers = {
        "timestamp_column": "date",
        "id_columns": [],
        "target_columns": ["close"],
        "control_columns": [] 
        } 


def create_test_sets():
    test_sets = []
    for ticker in tickers:
        df = pd.read_csv(f"./processed_data/{ticker}.csv", parse_dates=["date"])
        _, _, test_df = prepare_data_splits(df,context_length=512,split_config={"train": 0.6,"test": 0.4})
        test_sets.append(test_df)
    return test_sets

def predict_series( test_sets, pipeline, _type, event_title):
    for test_df,ticker,start,end in zip(test_sets,tickers,starts,ends):
        forecast = pipeline(test_df)
        forecast["date"]     = pd.to_datetime(forecast["date"])
        forecast["y_true"]   = forecast["close"].str[0]
        forecast["y_pred"]   = forecast["close_prediction"].str[0]
        forecast["residual"] = forecast["y_true"] - forecast["y_pred"]
        output_path          = os.path.join('fewshot_results', f'{_type}_predict_{ticker}.csv')
        forecast.to_csv(output_path, index=False)

        df = pd.read_csv(f"./processed_data/{ticker}.csv", parse_dates=["date"])
        forecast         = pipeline(df)
        start            = pd.to_datetime(start)
        end              = pd.to_datetime(end)
        mask             = (forecast["date"] >= start) & (forecast["date"] <= end)
        event            = forecast.loc[mask]
        event["y_true"]  = event["close"].str[0]
        event["y_pred"]  = event["close_prediction"].str[0]
        output_path      = os.path.join('fewshot_results',  f'{_type}_predict_{ticker}_event.csv')
        event.to_csv(output_path, index=False)


test_sets = create_test_sets()
idx = 0

for ticker,start,end,event_title in zip(tickers,starts,ends,event_titles):
    
    df = pd.read_csv(f"./processed_data/{ticker}.csv", parse_dates=["date"])

    
    preprocessor = TimeSeriesPreprocessor(
        **column_specifiers,
        context_length     = 512,
        prediction_length  = 96,
        scaling            = True,
        encode_categorical = False,
        scaler_type        = "standard",
    )
    
    preprocessor.train(df)

    model = TinyTimeMixerForPrediction.from_pretrained(
        load_path , 
        num_input_channels             = preprocessor.num_input_channels,
        prediction_channel_indices     = preprocessor.prediction_channel_indices,
        exogenous_channel_indices      = preprocessor.exogenous_channel_indices,
        fcm_use_mixer                  = False,
        enable_forecast_channel_mixing = False,
        decoder_mode                   = "mix_channel",
    )

    for param in model.backbone.parameters():
        param.requires_grad = False

    train_df, valid_df, test_df = prepare_data_splits(
        df,
        context_length=512,
        split_config={"train": 0.6,"test": 0.4}
    )

    train_set, valid_set, test_set = get_datasets(
        preprocessor,
        df,
        {"train": 0.6,"test": 0.4},
        fewshot_fraction    = 0.7,
        fewshot_location    = "first",
        use_frequency_token = model.config.resolution_prefix_tuning,
    )
    
    learning_rate  = 0.0004
    num_epochs     = 5
    patience       = 10
    batch_size     = 64

    args = TrainingArguments(
        output_dir                  = os.path.join('fewshot_results', "output"),
        overwrite_output_dir        = True,
        learning_rate               = learning_rate,
        num_train_epochs            = num_epochs,
        do_eval                     = True,
        eval_strategy               = "epoch",
        per_device_train_batch_size = batch_size,
        per_device_eval_batch_size  = batch_size,
        dataloader_num_workers      = 4,
        report_to                   = None,
        save_strategy               = "epoch",
        logging_strategy            = "epoch",
        save_total_limit            = 1,
        logging_dir                 = os.path.join('fewshot_results', "logs"),  
        load_best_model_at_end      = True,  
        metric_for_best_model       = "eval_loss",  
        greater_is_better           = False,  
        use_cpu                     = device != "cuda",
    )

    early_stopping_callback = EarlyStoppingCallback(
        early_stopping_patience=patience,
        early_stopping_threshold=0.00001, 
        )
    
    tracking_callback = TrackingCallback()

    optimizer = AdamW(model.parameters(), lr=learning_rate,weight_decay=0.01)
    scheduler = OneCycleLR(optimizer, learning_rate, epochs=num_epochs, steps_per_epoch=math.ceil(len(train_set) / (batch_size)),)

    trainer = Trainer(
        model         = model,
        args          = args,
        train_dataset = train_set,
        eval_dataset  = valid_set,
        callbacks     = [early_stopping_callback, tracking_callback],
        optimizers    = (optimizer, scheduler),
    )
    
    trainer.train()

    pipeline = TimeSeriesForecastingPipeline(
        model,
        device            = device, 
        feature_extractor = preprocessor,
        batch_size        = batch_size,
    )

    
    predict_series(
        test_sets,
        pipeline,
        f'finetune_on_{ticker}',
        event_title
    )

results = []
for ticker in tickers:
    path = os.path.join('fewshot_results', f'finetune_on_{ticker}_predict_{ticker}.csv')
    df = pd.read_csv(path)
    df = df.dropna(subset=["y_true", "y_pred"])
    m = metrics(df["y_true"].values, df["y_pred"].values)
    m["ticker"] = ticker
    results.append(m)        

    fewshot_df = pd.DataFrame(results).set_index("ticker")
    output_path = os.path.join("fewshot_results", "finetune_itself.csv")
    fewshot_df.to_csv(output_path)
print('\n\n','--------FINETUNE ITSELF--------')
print(fewshot_df)



for from_ticker in tickers:
    results = []
    for to_ticker in tickers:
        path = os.path.join('fewshot_results', f'finetune_on_{from_ticker}_predict_{to_ticker}.csv')
        df = pd.read_csv(path)
        df = df.dropna(subset=["y_true", "y_pred"])
        m = metrics(df["y_true"].values, df["y_pred"].values)
        m["ticker"] = to_ticker
        results.append(m)
    fewshot_df = pd.DataFrame(results).set_index("ticker")
    output_path = os.path.join("fewshot_results", f'finetune_on_{from_ticker}.csv')
    fewshot_df.to_csv(output_path)
    print('\n\n',f'--------FINETUNE ON {from_ticker}--------')
    print(fewshot_df)


results = []
for ticker in tickers:
    path = os.path.join('fewshot_results', f'finetune_on_{ticker}_predict_{ticker}_event.csv')
    df = pd.read_csv(path)
    df = df.dropna(subset=["y_true", "y_pred"])
    m = metrics(df["y_true"].values, df["y_pred"].values)
    m["ticker"] = ticker
    results.append(m)        

    fewshot_df = pd.DataFrame(results).set_index("ticker")
    output_path = os.path.join("fewshot_results", "finetune_itself_event.csv")
    fewshot_df.to_csv(output_path)
print('\n\n','--------FINETUNE ITSELF--------')
print(fewshot_df)


for from_ticker in tickers:
    results = []
    for to_ticker in tickers:
        path = os.path.join('fewshot_results', f'finetune_on_{from_ticker}_predict_{to_ticker}_event.csv')
        df = pd.read_csv(path)
        df = df.dropna(subset=["y_true", "y_pred"])
        m = metrics(df["y_true"].values, df["y_pred"].values)
        m["ticker"] = to_ticker
        results.append(m)
    fewshot_df = pd.DataFrame(results).set_index("ticker")
    output_path = os.path.join("fewshot_results", f'finetune_on_{from_ticker}_event.csv')
    fewshot_df.to_csv(output_path)
    print('\n\n',f'--------FINETUNE ON {from_ticker}--------')
    print(fewshot_df)

Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 40.07431750297546 seconds, Total Train Time = 390.87165880203247

Device set to use cpu
Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 40.79046792984009 seconds, Total Train Time = 391.16852593421936

Device set to use cpu
Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 40.15943489074707 seconds, Total Train Time = 391.8215298652649

Device set to use cpu
Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 40.05519704818725 seconds, Total Train Time = 369.6118595600128

Device set to use cpu
Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 36.21645965576172 seconds, Total Train Time = 348.28976607322693

Device set to use cpu
Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 43.34964022636414 seconds, Total Train Time = 420.1553599834442

Device set to use cpu
Some weights of TinyTimeMixerForPrediction were not initialized from the model checkpoint at ibm-granite/granite-timeseries-ttm-r2 and are newly initialized: ['decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.0.channel_feature_mixer.norm.norm.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.gating_block.attn_layer.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc1.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.mlp.fc2.weight', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.bias', 'decoder.decoder_block.mixers.1.channel_feature_mixer.norm.norm.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

[TrackingCallback] Mean Epoch Time = 43.680622243881224 seconds, Total Train Time = 426.82940435409546

Device set to use cpu

 --------FINETUNE ITSELF--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL    49.869907  59.544480  36.893818  0.475368   0.515645  0.504284
TSLA    29.913302  38.965486  17.623667  0.485790   0.510429  0.537468
XOM      4.026230   4.925996   6.471292  0.503519   0.507426  0.535248
SPY     26.794812  38.949912   7.103338  0.477287   0.521739  0.558473
JNJ      4.111497   5.747740   2.910442  0.498401   0.511860  0.529716
AMD     12.039214  16.689758  14.833533  0.471529   0.469166  0.512550
PG       2.436160   3.092036   1.953492  0.467051   0.501738  0.528694

              f1
ticker
AAPL    0.509901
TSLA    0.523600
XOM     0.520966
SPY     0.539481
JNJ     0.520635
AMD     0.489899
PG      0.514863


 --------FINETUNE ON AAPL--------
               mae        rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     49.869907   59.544480  36.893818  0.475368   0.515645  0.504284
TSLA    115.110716  167.168206  53.587190  0.491738   0.521108  0.510336
XOM      28.830708   36.000170  40.250871  0.489443   0.499382  0.527415
SPY      78.062592   93.942213  19.926571  0.477287   0.527431  0.504773
JNJ      22.840551   26.471841  15.992874  0.475368   0.490470  0.498708
AMD      53.348649   66.801295  59.760677  0.459373   0.457649  0.478203
PG       32.466423   35.370742  25.702502  0.475368   0.516896  0.504274

              f1
ticker
AAPL    0.509901
TSLA    0.515666
XOM     0.513016
SPY     0.515854
JNJ     0.494555
AMD     0.467700
PG      0.510507


 --------FINETUNE ON TSLA--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     6.390007   8.188823   5.106469  0.464491   0.501746  0.527540
TSLA    29.913302  38.965486  17.623667  0.485790   0.510429  0.537468
XOM      4.760269   6.147695   9.257288  0.495841   0.500618  0.528721
SPY     13.687294  17.880527   3.503974  0.486244   0.530286  0.553699
JNJ      3.532259   4.527255   2.492075  0.500960   0.515038  0.531008
AMD      9.995135  13.512480  11.313423  0.478567   0.477189  0.511229
PG       3.445179   4.381159   2.805160  0.470250   0.505869  0.526252

              f1
ticker
AAPL    0.514320
TSLA    0.523600
XOM     0.514286
SPY     0.541740
JNJ     0.522901
AMD     0.493622
PG      0.515859


 --------FINETUNE ON XOM--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     6.455720   8.208351   4.985993  0.479846   0.515909  0.555692
TSLA    20.701126  27.609907  10.787847  0.485129   0.506977  0.563307
XOM      4.026230   4.925996   6.471292  0.503519   0.507426  0.535248
SPY     12.072549  15.203982   3.135756  0.492003   0.533927  0.572792
JNJ      3.700793   4.417958   2.607948  0.506078   0.520860  0.532300
AMD      7.340976   9.561209   8.741567  0.471529   0.472727  0.515192
PG       4.042425   4.865909   3.177859  0.465771   0.500582  0.525031

              f1
ticker
AAPL    0.535062
TSLA    0.533660
XOM     0.520966
SPY     0.552677
JNJ     0.526518
AMD     0.493047
PG      0.512515


 --------FINETUNE ON SPY--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL    11.864963  15.749151   9.623637  0.472809   0.510345  0.543452
TSLA    67.214670  91.656429  39.539333  0.487773   0.512727  0.546512
XOM     11.103203  14.821019  23.205665  0.498401   0.504337  0.531332
SPY     26.794812  38.949912   7.103338  0.477287   0.521739  0.558473
JNJ      8.602789  11.210616   6.093391  0.500960   0.515567  0.534884
AMD     21.358232  30.584384  24.466261  0.477927   0.477189  0.511229
PG       6.664787   9.086971   5.369455  0.465131   0.500578  0.528694

              f1
ticker
AAPL    0.526378
TSLA    0.529081
XOM     0.517483
SPY     0.539481
JNJ     0.525048
AMD     0.493622
PG      0.514252


 --------FINETUNE ON JNJ--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     5.224527   7.529472   4.357391  0.481126   0.518059  0.561812
TSLA    33.816175  48.155185  20.910253  0.483807   0.507766  0.549096
XOM      5.212321   7.688754  11.700478  0.493922   0.498150  0.527415
SPY     12.327795  19.389991   3.321773  0.483045   0.526144  0.576372
JNJ      4.111497   5.747740   2.910442  0.498401   0.511860  0.529716
AMD     10.147683  15.841991  11.811904  0.474728   0.474065  0.519155
PG       2.783400   4.222732   2.230543  0.467690   0.502884  0.532357

              f1
ticker
AAPL    0.539049
TSLA    0.527623
XOM     0.512365
SPY     0.550114
JNJ     0.520635
AMD     0.495586
PG      0.517200


 --------FINETUNE ON AMD--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL    10.230439  12.626095   7.879345  0.476008   0.513083  0.552020
TSLA    36.322505  50.606543  21.124693  0.485790   0.509434  0.558140
XOM      7.628626   9.120396  14.224637  0.497121   0.502469  0.531332
SPY     21.712634  26.140079   5.718672  0.481126   0.525386  0.568019
JNJ      6.707625   8.003625   4.735217  0.504798   0.518057  0.537468
AMD     12.039214  16.689758  14.833533  0.471529   0.469166  0.512550
PG       6.255070   7.439785   4.905488  0.470889   0.505721  0.539683

              f1
ticker
AAPL    0.531840
TSLA    0.532676
XOM     0.516497
SPY     0.545872
JNJ     0.527584
AMD     0.489899
PG      0.522150


 --------FINETUNE ON PG--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     4.492060   5.913104   3.654361  0.476008   0.511945  0.550796
TSLA    18.232563  24.579306  10.374491  0.492399   0.515700  0.551680
XOM      2.643769   3.332902   4.650494  0.488804   0.493812  0.520888
SPY      8.230821  10.699342   2.178502  0.490083   0.532453  0.577566
JNJ      2.412834   3.100648   1.717041  0.502239   0.516169  0.536176
AMD      6.408386   8.753954   7.013585  0.471529   0.471515  0.513871
PG       2.436160   3.092036   1.953492  0.467051   0.501738  0.528694

              f1
ticker
AAPL    0.530660
TSLA    0.533084
XOM     0.506989
SPY     0.554093
JNJ     0.525982
AMD     0.491783
PG      0.514863


 --------FINETUNE ITSELF--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL    17.496619  20.793264  27.064881  0.425641   0.485714  0.481132
TSLA    36.599964  41.333092  19.949418  0.469231   0.493827  0.592593
XOM      4.119393   4.941102   6.024157  0.534615   0.575163  0.619718
SPY     71.032189  78.036835  18.675938  0.455598   0.387097  0.444444
JNJ      2.876184   3.697201   2.551294  0.453947   0.512195  0.515337
AMD      2.581716   3.024432  14.035761  0.447876   0.486111  0.522388
PG       1.089833   1.331642   1.807681  0.507042   0.482014  0.523438

              f1
ticker
AAPL    0.483412
TSLA    0.538721
XOM     0.596610
SPY     0.413793
JNJ     0.513761
AMD     0.503597
PG      0.501873


 --------FINETUNE ON AAPL--------
               mae        rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     17.496619   20.793264  27.064881  0.425641   0.485714  0.481132
TSLA    119.135047  175.779596  57.941107  0.465385   0.496063  0.466667
XOM      30.085690   34.450668  42.471888  0.507692   0.562500  0.570423
SPY     101.938871  132.790816  24.835780  0.521236   0.469231  0.564815
JNJ      18.586047   19.983138  15.959506  0.559211   0.627451  0.588957
AMD      12.241600   14.273567  64.152219  0.467181   0.507576  0.500000
PG        6.968508    8.159918  11.320651  0.415493   0.385185  0.406250

              f1
ticker
AAPL    0.483412
TSLA    0.480916
XOM     0.566434
SPY     0.512605
JNJ     0.607595
AMD     0.503759
PG      0.395437


 --------FINETUNE ON TSLA--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     3.495576   4.696783   5.008169  0.456410   0.500000  0.566038
TSLA    36.599964  41.333092  19.949418  0.469231   0.493827  0.592593
XOM      4.691000   5.693153   6.118585  0.534615   0.581081  0.605634
SPY     26.457654  30.888462   6.974994  0.471042   0.401639  0.453704
JNJ      2.420114   3.153247   2.146708  0.457237   0.515337  0.515337
AMD      1.986137   2.812365   9.776841  0.451737   0.489362  0.514925
PG       2.330178   2.665107   3.925001  0.510563   0.488889  0.515625

              f1
ticker
AAPL    0.530973
TSLA    0.538721
XOM     0.593103
SPY     0.426087
JNJ     0.515337
AMD     0.501818
PG      0.501901


 --------FINETUNE ON XOM--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     3.002866   3.567265   4.503161  0.461538   0.504000  0.594340
TSLA    22.290323  26.346232  11.885281  0.465385   0.488889  0.651852
XOM      4.119393   4.941102   6.024157  0.534615   0.575163  0.619718
SPY     18.825284  22.054960   4.860804  0.467181   0.394958  0.435185
JNJ      2.883228   3.494291   2.481472  0.453947   0.512048  0.521472
AMD      2.214606   2.819593  10.658248  0.471042   0.506757  0.559701
PG       1.189517   1.540716   2.023041  0.510563   0.485714  0.531250

              f1
ticker
AAPL    0.545455
TSLA    0.558730
XOM     0.596610
SPY     0.414097
JNJ     0.516717
AMD     0.531915
PG      0.507463


 --------FINETUNE ON SPY--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     4.152830   5.456349   6.210080  0.441026   0.491667  0.556604
TSLA    38.135067  41.109848  20.014912  0.469231   0.493750  0.585185
XOM      5.493091   6.454210   7.266782  0.530769   0.577181  0.605634
SPY     71.032189  78.036835  18.675938  0.455598   0.387097  0.444444
JNJ      6.334839   8.061107   5.656369  0.457237   0.512195  0.515337
AMD      2.752528   3.565267  16.045211  0.447876   0.485714  0.507463
PG       6.069867   7.082682  10.378665  0.500000   0.475177  0.523438

              f1
ticker
AAPL    0.522124
TSLA    0.535593
XOM     0.591065
SPY     0.413793
JNJ     0.513761
AMD     0.496350
PG      0.498141


 --------FINETUNE ON JNJ--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     2.590872   3.571704   3.721786  0.451282   0.495935  0.575472
TSLA    24.558410  29.808547  13.624130  0.457692   0.484848  0.592593
XOM      2.828215   3.559987   3.791087  0.538462   0.578947  0.619718
SPY     32.254377  39.173707   8.586946  0.451737   0.380165  0.425926
JNJ      2.876184   3.697201   2.551294  0.453947   0.512195  0.515337
AMD      1.775245   2.419417   9.110299  0.463320   0.500000  0.537313
PG       2.993232   3.718626   5.138002  0.503521   0.482014  0.523438

              f1
ticker
AAPL    0.532751
TSLA    0.533333
XOM     0.598639
SPY     0.401747
JNJ     0.513761
AMD     0.517986
PG      0.501873


 --------FINETUNE ON AMD--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     4.022310   4.992202   6.179501  0.446154   0.491803  0.566038
TSLA    15.288198  20.573558   7.908284  0.484615   0.502890  0.644444
XOM      6.284747   7.040901   9.038884  0.538462   0.580000  0.612676
SPY     34.330670  40.400568   9.012860  0.459459   0.386555  0.425926
JNJ      5.300774   6.039242   4.607718  0.470395   0.524390  0.527607
AMD      2.581716   3.024432  14.035761  0.447876   0.486111  0.522388
PG       2.737805   3.627719   4.726206  0.503521   0.474820  0.515625

              f1
ticker
AAPL    0.526316
TSLA    0.564935
XOM     0.595890
SPY     0.405286
JNJ     0.525994
AMD     0.503597
PG      0.494382


 --------FINETUNE ON PG--------
              mae       rmse       mape  hit_rate  precision    recall  \
ticker
AAPL     2.833429   4.066103   4.009617  0.451282   0.495935  0.575472
TSLA    29.627570  35.812370  16.509295  0.492308   0.508982  0.629630
XOM      3.428291   4.189975   4.736756  0.515385   0.563758  0.591549
SPY     14.204049  17.209271   3.730933  0.471042   0.398305  0.435185
JNJ      2.078304   2.627078   1.813791  0.444079   0.503067  0.503067
AMD      1.943729   2.727744   8.936039  0.451737   0.489796  0.537313
PG       1.089833   1.331642   1.807681  0.507042   0.482014  0.523438

              f1
ticker
AAPL    0.532751
TSLA    0.562914
XOM     0.577320
SPY     0.415929
JNJ     0.503067
AMD     0.512456
PG      0.501873